### PR TITLE
feat: add -j for make to use all cpu cores

### PR DESCRIPTION
**Pull request by tuananh**
add -j for make to use all cpu cores

### CODE REVIEW

**Comment by abhisheksoni27** [comment]
Great! This is awesome except it doesn't allow the users to change the number of CPUs used for compiling. Can you add an option to supply that value via the command line?

**Comment by tuananh** [comment]
i don't quite get it. you mean using environment variable?

**Comment by abhisheksoni27** [comment]
Could be. What I meant was, Right now you're using `require('os').cpus().length` to get the max length of cores available. But, what if someone doesn't want to use all the cores for compiling dlib? So, an option to specify how many cores to use, rather than using all the cores by default would be great.

**Comment by justadudewhohacks** [comment]
Nice, thanks for contributing!

**Pull request merged**
